# Generated by Django 3.1.3 on 2020-11-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='ime')),
                ('street', models.CharField(max_length=80, verbose_name='street')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('zip_code', models.CharField(max_length=30, verbose_name='zip code')),
                ('country', models.CharField(max_length=60, verbose_name='country')),
                ('tax_num', models.CharField(max_length=50, verbose_name='tax number')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25, verbose_name='status')),
                ('project_name', models.CharField(max_length=70, verbose_name='ime')),
                ('contractor', models.CharField(choices=[('regius', 'Regius'), ('tantus', 'Tantus')], max_length=30, verbose_name='contractor')),
                ('aug', models.BooleanField(verbose_name='Aug')),
                ('contract_num', models.CharField(max_length=60, verbose_name='contract number')),
                ('annex', models.BooleanField(verbose_name='annex')),
                ('project_start_date', models.DateField(verbose_name='project start')),
                ('project_end_date', models.DateField(verbose_name='project end')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='contract value')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hourly rate')),
                ('lw', models.BooleanField(verbose_name='LW')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80, verbose_name='street')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('zip_code', models.CharField(max_length=30, verbose_name='zip code')),
                ('country', models.CharField(max_length=60, verbose_name='country')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
