# Generated by Django 3.1.2 on 2020-12-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ime')),
                ('street', models.CharField(max_length=80, verbose_name='Ulica')),
                ('city', models.CharField(max_length=50, verbose_name='Mesto')),
                ('zip_code', models.CharField(max_length=30, verbose_name='Poštna št.')),
                ('country', models.CharField(max_length=60, verbose_name='Država')),
                ('tax_num', models.CharField(max_length=50, verbose_name='Davčna št.')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regius', 'Regius'), ('Tantus', 'Tantus')], max_length=50, verbose_name='Izvajalec')),
                ('street', models.CharField(max_length=60, verbose_name='Ulica')),
                ('city', models.CharField(max_length=40, verbose_name='Mesto')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Poštna št.')),
                ('country', models.CharField(default='Slowenien', editable=False, max_length=50, verbose_name='Država')),
                ('slo_tax_num', models.CharField(max_length=50, verbose_name='Davčna št.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('v teku', 'V teku'), ('končano', 'Končano'), ('storno', 'Storno'), ('na čakanju', 'Na čakanju')], max_length=25, verbose_name='status')),
                ('project_name', models.CharField(max_length=70, verbose_name='Ime projekta')),
                ('aug', models.BooleanField(null=True, verbose_name='Aüg')),
                ('contract_num', models.CharField(max_length=60, verbose_name='številka pogodbe')),
                ('annex', models.BooleanField(null=True, verbose_name='aneks')),
                ('project_start_date', models.DateField(verbose_name='Od')),
                ('project_end_date', models.DateField(verbose_name='Do')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pogodbena vrendost')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='urna postavka')),
                ('lw', models.BooleanField(null=True, verbose_name='LW')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.client')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_on_site_name', models.CharField(max_length=50, null=True, verbose_name='Vodja gradbišča s strani izvajalca')),
                ('resp_on_site_phone_num', models.CharField(max_length=50, null=True, verbose_name='Telefon - vodja gradbišča')),
                ('resp_on_site_email', models.EmailField(max_length=254, null=True, verbose_name='Email - vodja gradbišča')),
                ('resp_client_name', models.CharField(max_length=80, null=True, verbose_name='Odgovorna oseba s strani naročnika')),
                ('resp_client_phone_num', models.CharField(max_length=50, null=True, verbose_name='Telefon - naročnik')),
                ('resp_client_email', models.EmailField(max_length=254, null=True, verbose_name='Email - naročnik')),
                ('resp_contractor_name', models.CharField(max_length=50, null=True, verbose_name='Odgovorna oseba s strani izvajalca')),
                ('resp_contractor_phone_num', models.CharField(max_length=50, null=True, verbose_name='Telefon - izvajalec')),
                ('resp_contractor_email', models.EmailField(max_length=254, null=True, verbose_name='Email - izvajalec')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80, null=True, verbose_name='ulica')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='mesto')),
                ('zip_code', models.CharField(max_length=30, null=True, verbose_name='poštna št.')),
                ('country', models.CharField(max_length=60, null=True, verbose_name='država')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
