# Generated by Django 3.1.2 on 2020-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadress',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='mesto'),
        ),
        migrations.AlterField(
            model_name='projectadress',
            name='country',
            field=models.CharField(max_length=60, null=True, verbose_name='država'),
        ),
        migrations.AlterField(
            model_name='projectadress',
            name='street',
            field=models.CharField(max_length=80, null=True, verbose_name='ulica'),
        ),
        migrations.AlterField(
            model_name='projectadress',
            name='zip_code',
            field=models.CharField(max_length=30, null=True, verbose_name='poštna št.'),
        ),
    ]
