# Generated by Django 3.1.3 on 2020-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontactinfo',
            name='client_contract_signer',
            field=models.CharField(max_length=50, null=True, verbose_name='Zakonit zastopnik - naročnik'),
        ),
    ]
