# Generated by Django 3.1.2 on 2020-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201125_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_client_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email - naročnik'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_client_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Odgovorna oseba s strani naročnika'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_client_phone_num',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefon - naročnik'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_contractor_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email - izvajalec'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_contractor_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Odgovorna oseba s strani izvajalca'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_contractor_phone_num',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefon - izvajalec'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_on_site_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email - vodja gradbišča'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_on_site_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Vodja gradbišča s strani izvajalca'),
        ),
        migrations.AlterField(
            model_name='projectcontactinfo',
            name='resp_on_site_phone_num',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefon - vodja gradbišča'),
        ),
    ]
