# Generated by Django 3.1.3 on 2020-12-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcontactinfo_client_contract_signer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Od')),
                ('end', models.DateField(verbose_name='Do')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Vrednost')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
