# Generated by Django 3.1.3 on 2020-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201125_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.CharField(choices=[('Regius', 'Regius'), ('Tantus', 'Tantus')], max_length=30, verbose_name='izvajalec'),
        ),
    ]
