# Generated by Django 3.1.3 on 2020-12-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectanex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectanex',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
