# Generated by Django 3.1.3 on 2020-11-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201125_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Mesto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=60, verbose_name='Država'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(max_length=80, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_num',
            field=models.CharField(max_length=50, verbose_name='Davčna št.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(max_length=30, verbose_name='Poštna št.'),
        ),
    ]
