# Generated by Django 3.1.3 on 2020-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201212_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectanex',
            name='anex_num',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Številka aneksa'),
        ),
    ]
