# Generated by Django 3.1.2 on 2020-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201126_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annex',
            field=models.BooleanField(null=True, verbose_name='aneks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aug',
            field=models.BooleanField(null=True, verbose_name='Aüg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lw',
            field=models.BooleanField(null=True, verbose_name='LW'),
        ),
    ]
