# Generated by Django 3.1.3 on 2020-12-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectanex_anex_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Datum vpisa'),
        ),
    ]
