# Generated by Django 3.1.3 on 2020-12-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201212_2110'),
        ('documents', '0002_projectcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnexDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anex_doc', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
                ('anex_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.projectanex')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
