# Generated by Django 3.1.3 on 2020-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=40, verbose_name='Priimek')),
                ('company', models.CharField(choices=[('Regius', 'Regius'), ('Tantus', 'Tantus'), ('Dapira 1', 'Dapira 1')], max_length=50, verbose_name='Podjetje')),
                ('employed', models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], max_length=5, verbose_name='Zaposlen')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=50, null=True, verbose_name='Telefon')),
                ('resp_on_site_email', models.EmailField(max_length=254, null=True, verbose_name='Elektronski naslov')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Državljanstvo')),
                ('living_address', models.CharField(max_length=100, null=True, verbose_name='Stalno prebivališče')),
                ('temporary_address', models.CharField(max_length=100, null=True, verbose_name='Začasno prebivališče')),
                ('emso', models.CharField(max_length=30, null=True, verbose_name='EMŠO')),
                ('tax_num', models.CharField(max_length=50, null=True, verbose_name='Davčna št.')),
                ('insurance_num', models.CharField(max_length=50, null=True, verbose_name='Številka zavarovanja')),
            ],
        ),
    ]
