# Generated by Django 3.1.3 on 2020-12-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerinfo',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Delavec'),
        ),
    ]
