# Generated by Django 3.1.3 on 2020-12-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcontactinfo_client_contract_signer'),
        ('workers', '0002_workerinfo_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerinfo',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Začasno prebivališče'),
        ),
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_str', models.CharField(max_length=365, verbose_name='Zasedenost')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Delavec')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Začetek')),
                ('end_date', models.DateField(verbose_name='Konec')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projekt')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Delavec')),
            ],
        ),
    ]
