# Generated by Django 3.1.3 on 2020-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20201204_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerinfo',
            name='resp_on_site_email',
        ),
        migrations.AddField(
            model_name='workerinfo',
            name='emailemail',
            field=models.EmailField(max_length=254, null=True, verbose_name='Elektronski naslov'),
        ),
    ]
