# Generated by Django 3.1.3 on 2020-12-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20201204_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerinfo',
            old_name='emailemail',
            new_name='email',
        ),
    ]
