# Generated by Django 3.1.3 on 2020-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20201204_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerinfo',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Državljanstvo'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektronski naslov'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='emso',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='EMŠO'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='insurance_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Številka zavarovanja'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='living_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stalno prebivališče'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='phone_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='tax_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Davčna št.'),
        ),
    ]
